apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: jellyfin
    namespace: media
spec:
    interval: 1m0s
    chart:
        spec:
            chart: ./charts/jellyfin
            reconcileStrategy: ChartVersion
            sourceRef:
                kind: GitRepository
                name: jellyfin-git
            version: ">=2.1.0 <2.2"
    values:
        persistence:
            media:
                enabled: false
        runtimeClassName: nvidia
        volumes:
            - name: data
              persistentVolumeClaim:
                  claimName: media-volume
        volumeMounts:
            - name: data
              mountPath: /data
