apiVersion: v1
kind: Secret
metadata:
  name: arr-api-keys
  namespace: media
type: Opaque
stringData:
  PROWLARR_API_KEY: ENC[AES256_GCM,data:Kueq7xYSZFKZb0oIgEcTLyK9B5VdFnauQCWEXkJuQoY=,iv:yf0tLTcgJkP1MSqH1Yv6BH1xUqxMhZ1uXOyQ3RDYtL0=,tag:eW5cxnz6ZLn1if4FpGFmsA==,type:str]
  RADARR_API_KEY: ENC[AES256_GCM,data:2pO85kyfT2b6bvsDx4gQFkt0OWYxpJacPezVRLjVvBE=,iv:Yr+60knNXZTG+NqLrZeHrmf+Lx6rCbCA7r/fj/o0OmY=,tag:Hu9pdvTQJk2xmrs7pvq6WA==,type:str]
  RADARR_ANIME_API_KEY: ENC[AES256_GCM,data:ctO2NJhCYHPLd2pHenMsQgBk+PiqMcaHMBqIye1LeaU=,iv:COfMILA12j9ZH0msXdWPe+TzM3YlvnuaCVD/jWupYJ8=,tag:Yv5s11oWAx6NcP8vRC51SA==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:xYkhrWy4no3qp1TlGftagYrrNZK8YnRhk2EuoO32S7A=,iv:FY4Eun7Qb2fuBK7A9U21DWfu+GlIn9J6buXNFt5+cL8=,tag:yGMx46GIsFpTcw0zJI/uZQ==,type:str]
  SONARR_ANIME_API_KEY: ENC[AES256_GCM,data:C6lt+sVIF4ms3sRMbGai86qijZxIsKxEp8JJ35BBI4I=,iv:Kv11Kdi+vhU8PoVNg7gLcGM/yNGDanMJ0kWqXxrfk+0=,tag:MxRzV2sV9cFbqrRYgU7sdQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1pdsmvs22vq89pv0k6k9zfl3fk899cqehj2f7tx7j0tt6l66kuqssryqjlr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhelhlYTM0TU9OZzNhdDFK
        SmZCZG5EM0RQUmxpVEw4R1RteFJ5bForc0NBCkV6SVBhUXNJdHZXd25ud1dxZFls
        U056T3c4SUR3c1BZTXg5OUgxb2toUUEKLS0tIG56d3Z6SjI4dVIrcHkvbFJLSm5a
        K05JRlBqMUxvbGxNYnRYa0gwYnQyWUEKvKVbZki8RRyiXhwulpmm45K5I2EcorHs
        6JggbD2deAkJE7E8esOkcwZUVF8PckXBAA8dlkmnQ2ruAS/10DqvWQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1zjzywnjly7fm0mn22c64z5f8m45tne4ddplrrtx9q40y4kznacysvc9jxj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTWU1Y1V6eVdYcWhsekt2
        eDV0NGRiME1taERvNDRVU3hZd092Y0hTcHc4CmhzNnlIdHdFeWhUK1hram1NcEZD
        SDlwaDZ4c2JGT1ZOekM4VGJ2MER4dGMKLS0tIGJYbDBOUzZQeDJZSmJsNzloTWR3
        NlZ2ZE9VeXcxeVFmYW13QmwxcGtVa2sKqxdpRjTNR9xfxE6JImuGYylRChVjeeTT
        qS6gWs457t7gFR9O9JqtYLuw97houjrDd+0Dm1mQ5wn9YgNs6AlIoA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-02T17:56:48Z"
  mac: ENC[AES256_GCM,data:9aNIzIvqJdZJLN3rFe9pAi3/QI8xwIoqLp2YljjsfRiq7U89Yy2UBC53Yz4TkQfpcKyIz5y1Lv3yO/1RUbt3x8zLmlHcQAsdqB/leBvy/QS3aMsNn/QjSCiuGWHnxGOeSuT3t1Up+B1omDk3666giQioSiMptZ9WBFr0iIrUCdc=,iv:+qIzPQOGJmrq0uNM6prZ3vLihKJdslGvKaV1nesxv60=,tag:9gnwySE8TkdHxHBZj7yvNg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.3
