apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: arrs
spec:
  providerConfigRef:
    name: arrs
  forProvider:
    source: Remote
    module: "github.com/typedrat/homelab//terraform/arrs"
    env:
      - name: TF_VAR_radarrApiKey
        secretKeyRef:
          namespace: media
          name: arr-api-keys
          key: RADARR_API_KEY
      - name: TF_VAR_radarrAnimeApiKey
        secretKeyRef:
          namespace: media
          name: arr-api-keys
          key: RADARR_ANIME_API_KEY
      - name: TF_VAR_sonarrApiKey
        secretKeyRef:
          namespace: media
          name: arr-api-keys
          key: SONARR_API_KEY
      - name: TF_VAR_sonarrAnimeApiKey
        secretKeyRef:
          namespace: media
          name: arr-api-keys
          key: SONARR_ANIME_API_KEY
      - name: TF_VAR_prowlarrApiKey
        secretKeyRef:
          namespace: media
          name: arr-api-keys
          key: PROWLARR_API_KEY
