apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
    name: arrs
spec:
    credentials:
        - filename: radarr-api-key
          source: Secret
          secretRef:
              namespace: media
              name: arr-api-keys
              key: RADARR_API_KEY
        - filename: radarr-anime-api-key
          source: Secret
          secretRef:
              namespace: media
              name: arr-api-keys
              key: RADARR_ANIME_API_KEY
        - filename: sonarr-api-key
          source: Secret
          secretRef:
              namespace: media
              name: arr-api-keys
              key: SONARR_API_KEY
        - filename: sonarr-anime-api-key
          source: Secret
          secretRef:
              namespace: media
              name: arr-api-keys
              key: SONARR_ANIME_API_KEY
        - filename: prowlarr-api-key
          source: Secret
          secretRef:
              namespace: media
              name: arr-api-keys
              key: PROWLARR_API_KEY
    configuration: |
        terraform {
            backend "kubernetes" {
                secret_suffix     = "providerconfig-arrs"
                namespace         = "media"
                in_cluster_config = true
            }

            required_providers {
                radarr = {
                    source  = "devopsarr/radarr"
                    version = "2.3.2"
                }
                sonarr = {
                    source  = "devopsarr/sonarr"
                    version = "3.4.0"
                }
                prowlarr = {
                    source  = "devopsarr/prowlarr"
                    version = "3.0.2"
                }
            }
        }

        provider "radarr" {
            url     = "http://radarr.media.svc.cluster.local"
            api_key = file("${path.module}/radarr-api-key")
        }

        provider "radarr" {
            alias   = "anime"
            url     = "http://radarr-anime.media.svc.cluster.local"
            api_key = file("${path.module}/radarr-anime-api-key")
        }

        provider "sonarr" {
            url     = "http://sonarr.media.svc.cluster.local"
            api_key = file("${path.module}/sonarr-api-key")
        }

        provider "sonarr" {
            alias   = "anime"
            url     = "http://sonarr-anime.media.svc.cluster.local"
            api_key = file("${path.module}/sonarr-anime-api-key")
        }

        provider "prowlarr" {
            url     = "http://prowlarr.media.svc.cluster.local"
            api_key = file("${path.module}/prowlarr-api-key")
        }
