apiVersion: v1
kind: Service
metadata:
  name: flood
  namespace: media
spec:
  selector:
    app: flood-rtorrent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
  type: ClusterIP
