apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: flood
    namespace: media
    annotations:
        external-dns.alpha.kubernetes.io/target: iserlohn.thisratis.gay
spec:
    parentRefs:
        - name: gateway
          namespace: istio-ingress
          sectionName: wildcard-https
    hostnames:
        - flood.thisratis.gay
    rules:
        - matches:
              - path:
                    type: PathPrefix
                    value: "/"
          backendRefs:
              - name: flood
                port: 80
