apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
    name: flood-rtorrent
spec:
    providerConfigRef:
        name: authentik
    forProvider:
        source: Remote
        # https://github.com/typedrat/homelab/tree/00e872c/flood-rtorrent
        module: "github.com/typedrat/homelab//flood-rtorrent?ref=00e872c"
