apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
    name: flood-rtorrent
spec:
    providerConfigRef:
        name: authentik
    forProvider:
        source: Inline
        module: |
            data "authentik_flow" "default-authorization-flow" {
                slug = "default-provider-authorization-implicit-consent"
            }

            data "authentik_flow" "default-provider-invalidation-flow" {
                slug = "default-provider-invalidation-flow"
            }

            resource "authentik_provider_proxy" "name" {
                name               = "Flood"
                external_host      = "https://flood.ratsinthe.cloud"
                mode               = "forward_single"
                authorization_flow = data.authentik_flow.default-authorization-flow.id
                invalidation_flow  = data.authentik_flow.default-provider-invalidation-flow.id
            }

            resource "authentik_application" "name" {
                name              = "Flood"
                slug              = "flood"
                protocol_provider = authentik_provider_proxy.name.id
            }

             resource "authentik_service_connection_kubernetes" "local" {
                name  = "Local Kubernetes Cluster"
                local = true
            }

            resource "authentik_outpost" "proxy_outpost" {
                name               = "Proxy Outpost"
                protocol_providers = [ authentik_provider_proxy.name.id ]
                config             = jsonencode({
                authentik_host     = format("https://auth.ratsinthe.cloud")
                })
                service_connection = authentik_service_connection_kubernetes.local.id
            }
