apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
    name: flood-rtorrent
spec:
    providerConfigRef:
        name: authentik
    forProvider:
        source: Inline
        module: |
            data "authentik_flow" "default-authorization-flow" {
                slug = "default-provider-authorization-implicit-consent"
            }

            data "authentik_flow" "default-provider-invalidation-flow" {
                slug = "default-provider-invalidation-flow"
            }

            resource "authentik_provider_proxy" "name" {
                name               = "Flood"
                external_host      = "https://flood.ratsinthe.cloud"
                mode               = "forward_single"
                authorization_flow = data.authentik_flow.default-authorization-flow.id
                invalidation_flow  = data.authentik_flow.default-provider-invalidation-flow.id
            }

            resource "authentik_application" "name" {
                name              = "Flood"
                slug              = "flood"
                protocol_provider = authentik_provider_proxy.name.id
            }
