apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
  namespace: dragonfly-operator-system
spec:
  interval: 5m0s
  chartRef:
    kind: OCIRepository
    name: dragonfly-operator
    namespace: dragonfly-operator-system
