apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:rEmGsd4xWzOk8sgMIIonkKoBRllGMo2kLa2okYjokeiviNyxro3qUQ==,iv:CQK0O2wxtygXUnQW4Yw0guYThwSPjYtILTVNSKjGgVM=,tag:DzHJTEbhXvlgY0Un1cgqjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1psufqpzvwl74c4uqmt7y9f3akavrdzkevgfrg3d0rcw2nj7fwe7sctsjpe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcVFvUWNNQXkvU0RzeW1n
            UE93Q1YxUXpEZ3MyVFNxS3MrK1VsSDd2ZTBFClJHeWtJTWZscVRJTXpreU9nOGNM
            b3V1ZUx3MnFJN21WSFp0WnJBUFdIOW8KLS0tIFpKenRjR2g2amFpZXFGU0RWVCs0
            SFAxcjNpWldnVXJ5N3JGTTlzcHF3cjgKDZjzV8IrbfNyhcmbnprGKDXPqsFxWATe
            0MXbjzn+y7NT50tQGUCk14ZQLUyN+LJDCE/YS36380HlDsmPkj8pig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zjzywnjly7fm0mn22c64z5f8m45tne4ddplrrtx9q40y4kznacysvc9jxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQmhaTGhYNVF5OEJpNXdY
            QzB5Vjh6SGQ1OTNDRkp5eFlLMlVhTUdKZVdRCjlmV05BMkN0Um5QMHdOOS9jVHFF
            WktPa0RMZFVlRnZBZUpoaGg0bGd5dzQKLS0tIEtHYjdOVDlsMHhnbE96RUFMWG9G
            RGRaUDFpUkJGa1pqcmR2RE8vTFRrb3cK2HRBF3Nk11x3Nbd5Rz3S8x/qMw7AsAl6
            mFepWPJR/XbEq6wc0oUpFfkPMC18HePOUCyEuJjE9YApXw6PAjxieA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-26T07:25:13Z"
    mac: ENC[AES256_GCM,data:dzi/hNvgbxP4oHpPjhUKUPKW1FNjeqYt7idtNUAWD5kBCG+D8+DrdhMrRUYfqwxSk4CWPQSFopqPdD1cCQmmZoxbAEIuc6NIl45H8vLaXK5wh7lwo1BQIuca58T+aAnC663IrNFoIr2NBABt6PTuLU0Qk4iid7UiQRQcqQNbBmI=,iv:osCFG90qzLe6/ETwVw+WpK8LlRtc38/mTB29O6AUk18=,tag:MC9ARTR9RtqrwQaL44UqMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
