apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: webhook-receiver
    namespace: flux-system
    annotations:
        external-dns.alpha.kubernetes.io/target: iserlohn.thisratis.gay
spec:
    parentRefs:
        - name: gateway
          namespace: istio-ingress
          sectionName: wildcard-https
    hostnames:
        - flux-webhook.thisratis.gay
    rules:
        - matches:
              - path:
                    type: PathPrefix
                    value: /
          backendRefs:
              - kind: Service
                name: webhook-receiver
                port: 80
