creation_rules:
    - path_regex: (clusters|infrastructure)/.*\.yaml
      encrypted_regex: ^(data|stringData)$
      age: >-
          age1psufqpzvwl74c4uqmt7y9f3akavrdzkevgfrg3d0rcw2nj7fwe7sctsjpe,
          age1zjzywnjly7fm0mn22c64z5f8m45tne4ddplrrtx9q40y4kznacysvc9jxj

    - path_regex: secrets.yaml
      encrypted_regex: ^(secret|bootstraptoken|secretboxencryptionsecret|token|key)$
      age: >-
          age1psufqpzvwl74c4uqmt7y9f3akavrdzkevgfrg3d0rcw2nj7fwe7sctsjpe
