apiVersion: batch/v1
kind: CronJob
metadata:
    name: configarr
    namespace: media
spec:
    schedule: "0 * * * *" # Runs every hour
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                        - name: configarr
                          image: ghcr.io/raydak-labs/configarr:latest
                          imagePullPolicy: Always
                          tty: true
                          env:
                              - name: RADARR_API_KEY
                                secretKeyRef:
                                    namespace: media
                                    name: radarr-secrets
                                    key: api-key
                              - name: RADARR_ANIME_API_KEY
                                secretKeyRef:
                                    namespace: media
                                    name: radarr-secrets
                                    key: anime-api-key
                              - name: SONARR_API_KEY
                                secretKeyRef:
                                    namespace: media
                                    name: sonarr-secrets
                                    key: api-key
                              - name: SONARR_ANIME_API_KEY
                                secretKeyRef:
                                    namespace: media
                                    name: sonarr-secrets
                                    key: anime-api-key
                          volumeMounts:
                              - mountPath: /app/repos
                                name: app-data
                                subPath: configarr-repos
                              - name: config-volume
                                mountPath: /app/config/config.yml
                                subPath: config.yml
                    volumes:
                        - name: app-data
                          persistentVolumeClaim:
                              claimName: configarr-repo-cache
                        - name: config-volume
                          configMap:
                              name: configarr
                    restartPolicy: Never
