apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: configarr-repo-cache
    namespace: media
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
