apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: shoko-config
    namespace: media
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 5Gi
