apiVersion: v1
kind: Secret
metadata:
    name: credentials
    namespace: librechat
stringData:
    CREDS_KEY: ENC[AES256_GCM,data:WtPOY2mvDKb4UcWpejpv2Cug3m17Ni1vGTJOspURKyP3A2MGU2em2B9CO5xkb2+K1JRJsI33RamjB1aQgcWg5g==,iv:QeGHk+XBHuUXpZP9iR7GYSbWxg3mfd6g8bXeCy3ELk4=,tag:4YFZg66U5wBnI/cvARwaDw==,type:str]
    CREDS_IV: ENC[AES256_GCM,data:/uQgE0Bf6K3rSCxuj0ygSom0JYfFOHCB1mAzLin/JP4=,iv:yj0gAw5ppxNOmByEuUEZkfDBYpS13fhROzE+OZwWY1k=,tag:Npj0EBGJD7bs2vlTGwwxHA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:dhAvIjwgGq4vaWyAfTZVifLDKPjncBIhqAIv/GMfbGHn6Cjj3eCl0YANSnZgZC1PCUZ/vC3f8QVbqjGvC8lKqw==,iv:A5l33iGK/U9IYu2SgfALB8iImbENpMn25h4aJFwaGnk=,tag:EXvEvqCLWlPpCwZwOdXE1g==,type:str]
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:JszoGessQvDHKM2Vvfpj2J1mHDKyuqIdRx9cbT/keD+apaptIXZgfNt3a4xoobuSGM0PCaBmxwUN+Q661T3WjA==,iv:CiwDi8BnnkP0rEtSOJ3nnsfOeBXTUuvg/iVLMge4ao8=,tag:vzVTIeWQbc2aNuwMQHbWAA==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:8nThnfXrjg/eE7/Vxotpo67EycDlqATAOubiSo+Etzc=,iv:uB0qjj7qLrmf+/s9b6x99wp2nOOct/H47gU6Gi/tKqs=,tag:/3cTq/5xpV/shiwiG/FDYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pdsmvs22vq89pv0k6k9zfl3fk899cqehj2f7tx7j0tt6l66kuqssryqjlr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySVU1VDQrUjYwRzlWTVhR
            ZklkYXBDTnNOV244SGJLc0s4Z0lTK0wycFh3CkFWR0xwZTZBemNPRHhTOU45eElI
            b2FnbXBtNGorZkIybkZ2MkJGS0s4Z2cKLS0tIGpjOER4c1IrQmQ4Ky9OTllLbGgw
            QXd4NGp4a1FZbG9Rek0zUXErWVhLZVEKAKhO1T1P1BZO7fakb2Idy4bhQVfAU1Ox
            W5ARpNfXQD+IS/Zw/Hvokj7RVK1XpCw4UBsbXm4Ias/mSLB4mMEOpw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zjzywnjly7fm0mn22c64z5f8m45tne4ddplrrtx9q40y4kznacysvc9jxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMUVKNUhJYzdyRFJ4cGdM
            U1ZjWW9wQURwaGwza0NhUHlFSk94SG8zN3dNCkZRU2RhcXhJYkVwSWt0VDJLeU1U
            Rk1DTnI1aHp5RHRESXNoVUgveVBwckUKLS0tIGpBMlhlbWhBOFowalJqM1gxWk1S
            dUhNUUtuaDZSTEg2a2NmTElGQVBubUEKjTY8dXRLoDAd+mMUP1XqzccJJ8AMOJBN
            eEMNHay/IMh/P5DnnMYyUY0tAxgZ92VkIe9NlBsbLTaQOtdiE7qmvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-22T23:24:21Z"
    mac: ENC[AES256_GCM,data:076u1w0N1ELbHZVIQAtkGBw9WSqls5a+vyGJThs9n3M3u/afNz3WrSMNkV+yZnzClmINMXoRC0owDmk9qzUp37Xie6twvqPQ7J7nRPu6YJM2mie+sLfgO5lYq4h1hpLFyREVQ5ZMarp8TpczLP/ihxQcCPqDYQMoMGiR8DFcVJk=,iv:ujb+ZMyAFQF5atqJ4oIIsvJF0o/c7UQDlC5g50Ay1Cc=,tag:DGf0BvX15EOydT7izU/gPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
