apiVersion: v1
kind: Secret
metadata:
    name: mongodb-password
    namespace: librechat
stringData:
    password: ENC[AES256_GCM,data:JcjrjjhE4Nt/qhmapMVDTy2hVJy1dppB7osNGGkDUbZDJlfGIDdvxvkzFnKxJX/DSsoh3N30rFYsUsJoNpqVEwrBRlQZJqXwDb5Cm9YZPIwS0bPxXsN3ZBK9B1Yy3QHYQhMq8yckrgEIyNvl2vTCqFr5XH3KjHxEosyAEQzB9Hw=,iv:S2snkgWbotHIBwgE/b2oPP9UiQmWlbnD2/fFypF/YjI=,tag:Gu47AUbm+mFv/KhEgvNeTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pdsmvs22vq89pv0k6k9zfl3fk899cqehj2f7tx7j0tt6l66kuqssryqjlr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNWI5VzduTGpkckx4N2hM
            L3EzVk1pb1RtTGZjSUZEeGZwQ3F3ODRpWVZNCnFJWHVEdGZQVFdwNmptOG8vOGFE
            MnNZWXNxVCtPblo1NWpGUGkwRTQ2UGsKLS0tIGVMZzlHN2pKWGNNa1FGNGcxRXJm
            UE4rQW9FcTU1a2hQblladTBlcUhmUk0KtPcApVL7RhbEI+wU1EA8jR1/q/YRE/xQ
            Hl2GRmYg30Jtdmuwcsho98AGFvoVryzHiYxZZq7pJ8jlm9UgTtpc7g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zjzywnjly7fm0mn22c64z5f8m45tne4ddplrrtx9q40y4kznacysvc9jxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUGovWDNVU2lLdEZVWThG
            V2JsQWpmeVo2cGJxMytlbklva1VUQUlJQTBNCmFqbGpNWnZ5M0Y4S1ZWOHRYcnp2
            dHFCZmZscWpPZHpCVXRvUXV6SFVSajAKLS0tIHFOUm11c1lnQmx4WVYxa1BZVlNT
            YVBhZUlxdHZhWTJmL3lBVUZmOE5jbk0KMiGGSUQpA0xEMG/+rYBVodvtSAaqNjgc
            VUTreDQeoMP2zt0D6A84kSv/VAQ5DpV9UJSgN234uFlrPPFk/dtD/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-22T23:28:22Z"
    mac: ENC[AES256_GCM,data:awNxZztcGo+7Qvyf18c1ZAbHR/dGcFO5eQnFCGr/HDRP2ZZWJ6YV2Rv3gcPycIUoT5XmxCP8AXpJ1lsZE6cl3dWZ9j07cvnXgFEK7FZZDIACo+6kqOXN4iOPN6QUTzikuP3pWOezq8Tf2qgCgaUv5cn9MC7WIXiQDZqdNoA4JFg=,iv:+jkTndUjmjiK4qAFnILhPin8juZr8wTB2n9dsqUfSxg=,tag:Psw6L2JO9GTSM+0GT2H0cQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
