apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret-key
    namespace: authentik
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:pSMwU5Oj9WcvXhEHdS8/o3p4Wj2XoE+2SsoGzDsscyLqmEVifchVWiSwP0vNprRnxw4=,iv:KHoXUk92PU5VmaevnTnVaQjDaDmtSPqgz/Vku6FzWec=,tag:6Y8si+lVz73EtJ2A/94rJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1psufqpzvwl74c4uqmt7y9f3akavrdzkevgfrg3d0rcw2nj7fwe7sctsjpe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UERBeEVucm41SWNiYjlt
            QXFQbzlRUVg0enJySzZQcmlLUTJsMVNJYTBvCkNxVkxmZlEwbTVjZ0VJUWVINXZk
            dE9KSnZHQ2lLeXV5ZjhDVWhwZ2huSmMKLS0tIERHQmdTbUdCaXpYSnBhWTRPRWR4
            U3pvM2pVR3pybHU2SlcrL05QQ1RTQ0EK/4CSNsJJb98fcMjKNzMlYIjtSa6oLTYI
            Q8ApIHJopAIMfDA2n9rxtgnzwWG2qSn8CwOzb/kgYQO1QpPKSUN+BQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zjzywnjly7fm0mn22c64z5f8m45tne4ddplrrtx9q40y4kznacysvc9jxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSis3STBOY0tudTdLQith
            NDdQYkhGZWhSa0RKWTRXbUUzdjAyRzQwcW5ZClcvalpLaWRvTVRMNU9ZVUxUNHow
            L1YwcjNlNGxwZFpnT3pOaUhOZC9UcFkKLS0tIEFRdnk3cFpjcC81WEorUW1RNlFL
            Vko2eFB5RHcrNU90NWgvRkFkZ2luZ0EKJNaxWO4y8mPwH5T3WvnRobXSwrV3W+hK
            wdJD66eAzmFgz1vuNeHtTOuqnf7vyRasjD4W/VcYqKdGBEwpjB5OOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-26T05:36:11Z"
    mac: ENC[AES256_GCM,data:kpJBr0bvatUHflnhBC+e/e11MqyLUK0hpEvMilJA9GbBwmTCAKFtLooSyJirm1iGYwzlnsseoFbJaDipzhK5ECwicYUiiL+y4LIghVaJYxMNBbxGondHOiws5Pv81bJk606UqUb5M9jeF3s+XHT5iL4rZetAg6XlOa34bkVuGcs=,iv:uqtHByWogDpCuiOlQMgzeXmU9q5jNGhymnhUWd4wuHU=,tag:vr0yd1nWFEy7hv+e4R+rXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
