apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
    name: dragonfly
    namespace: authentik
spec:
    replicas: 1
    persistentVolumeClaimSpec:
        accessModes:
            - ReadWriteOnce
        resources:
            requests:
                storage: 2Gi
        storageClassName: host-zfs-standard
