apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: httproute
    namespace: authentik
spec:
    parentRefs:
        - name: gateway
          namespace: istio-ingress
          sectionName: wildcard-https
    hostnames:
        - auth.ratsinthe.cloud
    rules:
        - matches:
              - path:
                    type: PathPrefix
                    value: "/"
          backendRefs:
              - name: authentik
                port: 9000
