apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: httproute
    namespace: authentik
    annotations:
        external-dns.alpha.kubernetes.io/target: iserlohn.thisratis.gay
spec:
    parentRefs:
        - name: gateway
          namespace: istio-ingress
          sectionName: wildcard-https
    hostnames:
        - auth.ratsinthe.cloud
    rules:
        - matches:
              - path:
                    type: PathPrefix
                    value: /if/flow/default-authentication-flow/
          filters:
              - type: RequestRedirect
                requestRedirect:
                    path:
                        type: ReplacePrefixMatch
                        replacePrefixMatch: /source/oauth/login/discord/
        - filters:
              - type: RequestHeaderModifier
                requestHeaderModifier:
                    add:
                        - name: X-Forwarded-Proto
                          value: https
                        - name: Host
                          value: auth.ratsinthe.cloud
          backendRefs:
              - name: authentik-server
                port: 80
