apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
    - repository.yaml
    - release.yaml
    - authentik-postgres.yaml
    - dragonfly.yaml
    - httproute.yaml
    - authentik-secret-key.yaml
secretGenerator:
    - name: authentik-values
      files:
          - values.yaml
configurations:
    - kustomizeconfig.yaml
