apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: authentik
    namespace: authentik
spec:
    interval: 1m0s
    chart:
        spec:
            chart: authentik
            reconcileStrategy: ChartVersion
            sourceRef:
                kind: HelmRepository
                name: authentik
            version: ">=2024.12.2 <2024.13"
    values:
        authentik:
            secretKey: file:///secret-key/secret-key
            error_reporting:
                enabled: true
            postgresql:
                host: authentik-postgres
                user: file:///postgres-creds/username
                password: file:///postgres-creds/password
            redis:
                host: dragonfly
        global:
            fullnameOverride: authentik
            volumes:
                - name: postgres-creds
                  secret:
                      secretName: authentik-postgres-app
                - name: secret-key
                  secret:
                      secretName: authentik-secret-key
            volumeMounts:
                - name: postgres-creds
                  mountPath: /postgres-creds
                  readOnly: true
                - name: secret-key
                  mountPath: /secret-key
                  readOnly: true
