apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
    name: authentik
spec:
    credentials:
        - filename: authentik-credentials
          source: Secret
          secretRef:
              namespace: authentik
              name: authentik-env
              key: AUTHENTIK_BOOTSTRAP_TOKEN
    configuration: |
        provider "authentik" {
            url      = "https://auth.thisratis.gay"
            token    = file("${path.module}/authentik-credentials")
        }

        // Modules _must_ use remote state. The provider does not persist state.
        terraform {
            backend "kubernetes" {
                secret_suffix     = "providerconfig-authentik"
                namespace         = "authentik"
                in_cluster_config = true
            }

            required_providers {
                authentik = {
                source  = "goauthentik/authentik"
                version = "2024.12.0"
                }
            }
        }
