apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
    name: authentik
spec:
    providerConfigRef:
        name: authentik
    forProvider:
        source: Remote
        # https://github.com/typedrat/homelab/tree/0156cff5/authentik
        module: "github.com/typedrat/homelab//authentik?ref=0156cff5"
        env:
            - name: TF_VAR_discordKey
              secretKeyRef:
                  name: authentik-discord
                  namespace: authentik
                  key: client-id
            - name: TF_VAR_discordSecret
              secretKeyRef:
                  name: authentik-discord
                  namespace: authentik
                  key: client-secret
            - name: TF_VAR_guildId
              secretKeyRef:
                  name: authentik-discord
                  namespace: authentik
                  key: guild-id
            - name: TF_VAR_guildName
              secretKeyRef:
                  name: authentik-discord
                  namespace: authentik
                  key: guild-name
            - name: TF_VAR_userRoleId
              secretKeyRef:
                  name: authentik-discord
                  namespace: authentik
                  key: user-role-id
            - name: TF_VAR_sysopRoleId
              secretKeyRef:
                  name: authentik-discord
                  namespace: authentik
                  key: sysop-role-id
            - name: TF_VAR_jellyfinKey
              secretKeyRef:
                  name: authentik-jellyfin
                  namespace: authentik
                  key: client-id
            - name: TF_VAR_jellyfinSecret
              secretKeyRef:
                  name: authentik-jellyfin
                  namespace: authentik
                  key: client-secret
