apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: metrics-server
    namespace: kube-system
spec:
    interval: 10m0s
    chart:
        spec:
            chart: metrics-server
            reconcileStrategy: ChartVersion
            sourceRef:
                kind: HelmRepository
                name: metrics-server
            version: ">=0.7.2 <0.8"
