apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: metrics-server
    namespace: kube-system
spec:
    interval: 10m0s
    url: https://kubernetes-sigs.github.io/metrics-server/
