apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth
    namespace: monitoring
stringData:
    client-id: ENC[AES256_GCM,data:6H7c/XP5VtXNALPW70SE3vOlXGdibbvXJXm7HzljfqEWkCTswDwoLQ==,iv:DQBHNVtvCH/eETC0sQ0dPDaCQ/Eez30xO3Y8JYhncLc=,tag:Bcfxyhujw5KrnuPN1ffIig==,type:str]
    client-secret: ENC[AES256_GCM,data:04EpKOOv/AO3OQUkwWHA2781jryEZ1GqG8e6tEH/7NqwWMt8J6N5tR+h+aChho3KsDjFafGcQo51KGC/tlAfr0LXYRd6kZTAGpMmRhJF8hVWDbqOruluYEqTs1ZI0vcS9zre9qFQzvhajigcFaZDjTrjZFlR4hWI7uR+3kqiZWw=,iv:Q6vpYciaLaHYkyNGPeM28LoGjSa9ls4aM2twm33wiW8=,tag:CnwVcX0QHdtjY0M469yeXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1psufqpzvwl74c4uqmt7y9f3akavrdzkevgfrg3d0rcw2nj7fwe7sctsjpe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTDd0OUZNWUFlMUp1dmhN
            azE5VzdBdGMvTUgyUlhrVHJONXNGbDhDNGdJClV1ZFlocUFYUmRVYndydDNDNTJ2
            UW9QME1XZ2xNM3dZbXRMN3ZkK0RjdnMKLS0tIElUakdxbnpPRlVaajRyZUxnVjdx
            amp5d0FSNFg5QUlMSXVrQmVIUnJndEUK6jBDSLMTlLjXQeCcar7xW/Bn5LH797v9
            7XLeKl7mjwHA/49e+9VFYg/rLwCsoouci9vKVZicFdUxdM/if5x6Yg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zjzywnjly7fm0mn22c64z5f8m45tne4ddplrrtx9q40y4kznacysvc9jxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQkpKTURlSTRJdllOTFVx
            K0xRQ2FqNVJRRCtNdmZFcTJTaG5vQWNhaTFVCnowSWsvNnIvTCtSUFlpMkRNdG9P
            MjlYOExxKzgzckRnN1lOaXhWTWRtL0EKLS0tIDNTQkpYOVpYVnd2TktaczNrU0VS
            Umljd1d0cHRFT1NaaDlja0kzdnFLWEkKOv+6mk9zDbDIc0/sOFXEEIJ7aQWN9CL9
            ITNyDetAndoLT1DRSJ2H5J2kqmDYeFzW5C/iH96JwGLN9Vsrqq870w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-01T00:19:17Z"
    mac: ENC[AES256_GCM,data:3iMxeMeau6OUxLLGklL2vUCzyTnjChXXG0i77RoJHa1iaiMEmf6gkoQmScxY7Rmz505SJMvrxJWVJihGvoVQC7SXB6odTXoWAP3+kC81BO6oTtczA5s44bKk4DdWR/GKg9mnIpqZRik5lUEaRXl9U+26bMwjvyhqD2djMEjXNTE=,iv:rhyjeUOrWi5ar4A1TizOUbOp+i8uOXZuoApWiuuRZIA=,tag:OjI+QrmuUlSZ9QB2ChJZtg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
