apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: kube-prometheus-stack
    namespace: monitoring
spec:
    interval: 5m
    chart:
        spec:
            chart: kube-prometheus-stack
            version: ">=68.4.0 <68.5"
            sourceRef:
                kind: HelmRepository
                name: prometheus-community
                namespace: monitoring
            interval: 10m
    values:
        kubeControllerManager:
            endpoints:
                - 10.0.0.10

        kubeEtcd:
            endpoints:
                - 10.0.0.10
            service:
                selector:
                    component: etcd
            serviceMonitor:
                scheme: http
                serverName: localhost

        kubeProxy:
            enabled: false

        kubeScheduler:
            endpoints:
                - 10.0.0.10
