apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: kube-prometheus-stack
    namespace: monitoring
spec:
    interval: 5m
    chart:
        spec:
            chart: kube-prometheus-stack
            version: ">=68.4.0 <68.5"
            sourceRef:
                kind: HelmRepository
                name: prometheus-community
                namespace: monitoring
            interval: 10m
    values:
        kubeControllerManager:
            endpoints:
                - 10.0.0.10

        kubeEtcd:
            endpoints:
                - 10.0.0.10
            service:
                selector:
                    component: etcd
            serviceMonitor:
                scheme: https
                insecureSkipVerify: false
                serverName: "localhost"
                caFile: "/etc/prometheus/secrets/etcd-client-cert/etcd-ca.crt"
                certFile: "/etc/prometheus/secrets/etcd-client-cert/etcd-client.crt"
                keyFile: "/etc/prometheus/secrets/etcd-client-cert/etcd-client-key.key"
        kubeProxy:
            enabled: false

        kubeScheduler:
            endpoints:
                - 10.0.0.10

        prometheus:
            prometheusSpec:
                secrets:
                    - etcd-client-cert
                serviceMonitorSelectorNilUsesHelmValues: false

        grafana:
            grafana.ini:
                auth:
                    signout_redirect_url: "https://auth.thisratis.gay/application/o/grafana/end-session/"
                    oauth_auto_login: true
                auth.basic:
                    enabled: false
                auth.generic_oauth:
                    name: authentik
                    enabled: true
                    client_id: $__file{/etc/secrets/auth_generic_oauth/client_id}
                    client_secret: $__file{/etc/secrets/auth_generic_oauth/client_secret}
                    scopes: "openid profile email"
                    auth_url: "https://auth.thisratis.gay/application/o/authorize/"
                    token_url: "https://auth.thisratis.gay/application/o/token/"
                    api_url: "https://auth.thisratis.gay/application/o/userinfo/"
                    role_attribute_path: contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'

            extraSecretMounts:
                - name: authentik-grafana-secret-mount
                  secretName: authentik-grafana
                  namespace: authentik
                  defaultMode: 0440
                  mountPath: /etc/secrets/auth_generic_oauth
                  readOnly: true
