apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: clustersecret
    namespace: clustersecret
spec:
    interval: 5m
    chart:
        spec:
            chart: cluster-secret
            version: ">=0.2.1 <0.3.0"
            sourceRef:
                kind: HelmRepository
                name: clustersecret
                namespace: clustersecret
            interval: 1m
    install:
        createNamespace: true
