apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: monitoring-controllers
    namespace: flux-system
spec:
    interval: 10m0s
    path: ./monitoring/controllers
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
