---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: istio-ingress
    namespace: istio-ingress
spec:
    interval: 5m0s
    dependsOn:
        - name: istio-cni
          namespace: istio-system
        - name: ztunnel
          namespace: istio-system
    chart:
        spec:
            chart: gateway
            reconcileStrategy: ChartVersion
            sourceRef:
                kind: HelmRepository
                name: istio
                namespace: istio-system
            version: ">=1.24.2 <1.25"
    install:
        createNamespace: true
