apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-ingress
resources:
    - namespace.yaml
    # Gateway API CRDs:
    - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/experimental-install.yaml
    - gateway.yaml
    - redirect-to-https.yaml
