apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: authentik
    namespace: flux-system
spec:
    interval: 10m0s
    path: ./apps/authentik
    prune: true
    dependsOn:
        - name: istio-ingress
        - name: cnpg
        - name: dragonfly-operator
        - name: crossplane-terraform
    sourceRef:
        kind: GitRepository
        name: flux-system
    decryption:
        provider: sops
        secretRef:
            name: sops-age
