apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: podinfo
    namespace: flux-system
spec:
    interval: 10m0s
    path: ./apps/podinfo
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
