apiVersion: v1
kind: Pod
metadata:
    name: zfs-shell
    namespace: openebs
spec:
    hostIPC: true
    hostNetwork: true
    hostPID: true
    containers:
        - command: ["sleep", "infinity"]
          image: debian
          name: shell
          securityContext:
              privileged: true
