apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: external-dns
    namespace: external-dns
spec:
    interval: 5m0s
    chart:
        spec:
            chart: external-dns
            reconcileStrategy: ChartVersion
            sourceRef:
                kind: HelmRepository
                name: external-dns
            version: ">=1.15 <1.16"
    values:
        provider:
            name: cloudflare
        sources:
            - gateway-httproute
            - gateway-grpcroute
            - gateway-tlsroute
            - gateway-tcproute
            - gateway-udproute
        env:
            - name: CF_API_TOKEN
              valueFrom:
                  secretKeyRef:
                      name: cloudflare-api-token-secret
                      key: api-token
