---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: istiod
    namespace: istio-system
spec:
    interval: 5m0s
    dependsOn:
        - name: istio-base
          namespace: istio-system
    chart:
        spec:
            chart: istiod
            reconcileStrategy: ChartVersion
            sourceRef:
                kind: HelmRepository
                name: istio
            version: ">=1.24.2 <1.25"
    values:
        profile: ambient
        env:
            PILOT_ENABLE_ALPHA_GATEWAY_API: "true"
        meshConfig:
            extensionProviders:
                - name: "authentik"
                  envoyExtAuthzHttp:
                      service: "ak-outpost-proxy-outpost.authentik.svc.cluster.local"
                      port: "9000"
                      pathPrefix: "/outpost.goauthentik.io/auth/envoy"
                      headersToDownstreamOnAllow:
                          - cookie
                      headersToUpstreamOnAllow:
                          - set-cookie
                          - x-authentik-*
                      includeRequestHeadersInCheck:
                          - cookie
