---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: istiod
    namespace: istio-system
spec:
    interval: 5m0s
    dependsOn:
        - name: istio-base
          namespace: istio-system
    chart:
        spec:
            chart: istiod
            reconcileStrategy: ChartVersion
            sourceRef:
                kind: HelmRepository
                name: istio
            version: 1.24.2
    values:
        profile: ambient
