apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: podinfo
    namespace: podinfo
spec:
    interval: 5m
    chart:
        spec:
            chart: podinfo
            version: ">=6.7.1 <6.8"
            sourceRef:
                kind: HelmRepository
                name: podinfo
                namespace: podinfo
            interval: 1m
    install:
        createNamespace: true
    values:
        ingress:
            enabled: true
            className: istio
            hosts:
                - host: podinfo.ratsinthe.cloud
                  paths:
                      - path: /
                        pathType: Prefix
