apiVersion: v1
kind: Secret
metadata:
    name: sonarr-api-key
    namespace: media
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:pbRjUjj4Y4rAFwjGVnDtX8iSSgqrAkSF38ImeZfer4s=,iv:uP3xguj9TNVUM+WSa8fCtL0B2RyQSSfqpedVG7Y3JiY=,tag:2HKBkHs66/CUoyFmlWu22Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1psufqpzvwl74c4uqmt7y9f3akavrdzkevgfrg3d0rcw2nj7fwe7sctsjpe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucEpBVmJCWk4ySEFRcWpS
            S1VjN3NKTXJackp0dWcvZEZ5NjRTU2pvbkRZCjVXWTYwOFFiU2YrSWd6a0hQdEZn
            QkltaGNHVTI3R3pRNjVMb1g2UXNwU1UKLS0tIEs3NUhrR1lhVmhmSDZuWUorRENN
            ZDNFK2pyKytlMWl5UXNoY21TNVVRbkUKYyHdEM/v0wvEVxwgDz+uLRYJD1SwwjmS
            XksjhV0/r/AkI+bNnzxrgAdPJQ5u4vT/KyYxeC+I+PrtyPtCFssDYQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zjzywnjly7fm0mn22c64z5f8m45tne4ddplrrtx9q40y4kznacysvc9jxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NXU3S1d2VHZjNjF3U0Qx
            SjlFampZam95eDdQMWR4YS81b3Bhd094ZEJNCjhkcFRpTTUwYkFTajJhNjlyNGpx
            SzJTb3h6dWowVERUS0lPZUVvNWVlMFkKLS0tIHUzMkV1VnZQdlI4VnpZN3VnVlgx
            WnY2YXNEalJyVEduWGJBSitacGdXV2sKrxgA/YyyNOny883DFAAqHtJr9a9bRjfv
            oFPgheFm1MvSXD4goI4w6wCMwZZeZ74DwPf4r4+sk9gyWXmDQf5/Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-29T03:24:28Z"
    mac: ENC[AES256_GCM,data:msIvF0Ua21Kypd/Pj9sxi7lej+CY96xAuq6CeBAdOoDhEgK/vexi0UMpcrhx1dgzQ6ERGuhlb54CHmyxrUtXZ5PaA12JVXQ1mvDYGjO5QLmW/X+54i8MkC5eITOboyUOEIz510WHVs4/yT9GMbi9gxcy1uADfRnJk4OvdWTWyZQ=,iv:qMyCfJVrSjx64F/8Afhf4Zb8bcNsLQaNkChAFiRh5i4=,tag:um30auFRCxVuef4crcIMHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
