apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: sonarr-config
    namespace: media
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: host-zfs-standard
    resources:
        requests:
            storage: 1Gi
