apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: sonarr-postgres
    namespace: media
spec:
    instances: 1
    bootstrap:
        initdb:
            database: sonarr_main
            owner: sonarr
            dataChecksums: true
            localeCollate: "en_US"
            localeCType: "en_US"
            postInitSQL:
                - CREATE DATABASE sonarr_log OWNER sonarr
    storage:
        size: 1Gi
        storageClass: host-zfs-postgres
