apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m0s
  chartRef:
    kind: OCIRepository
    name: sonarr
    namespace: media
  values:
    securityContext:
      runAsUser: 911
      runAsGroup: 911
    podSecurityContext:
      fsGroup: 911

    extraEnv:
      - name: SONARR__APP__INSTANCENAME
        valueFrom:
          configMapKeyRef:
            name: sonarr-config
            key: instance-name

      - name: SONARR__AUTH__APIKEY
        valueFrom:
          secretKeyRef:
            name: arr-api-keys
            key: SONARR_API_KEY
      - name: SONARR__AUTH__METHOD
        value: External

      - name: SONARR__POSTGRES__HOST
        valueFrom:
          secretKeyRef:
            name: sonarr-postgres-app
            key: host
      - name: SONARR__POSTGRES__PORT
        valueFrom:
          secretKeyRef:
            name: sonarr-postgres-app
            key: port
      - name: SONARR__POSTGRES__USER
        valueFrom:
          secretKeyRef:
            name: sonarr-postgres-app
            key: user
      - name: SONARR__POSTGRES__PASSWORD
        valueFrom:
          secretKeyRef:
            name: sonarr-postgres-app
            key: password
      - name: SONARR__POSTGRES__MAINDB
        value: sonarr_main
      - name: SONARR__POSTGRES__LOGDB
        value: sonarr_log

    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: media-volume
    volumeMounts:
      - name: data
        mountPath: /data
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr-anime
  namespace: media
spec:
  interval: 5m0s
  chartRef:
    kind: OCIRepository
    name: sonarr
    namespace: media
  values:
    securityContext:
      runAsUser: 911
      runAsGroup: 911
    podSecurityContext:
      fsGroup: 911

    extraEnv:
      - name: SONARR__APP__INSTANCENAME
        valueFrom:
          configMapKeyRef:
            name: sonarr-config
            key: anime-instance-name

      - name: SONARR__AUTH__APIKEY
        valueFrom:
          secretKeyRef:
            name: arr-api-keys
            key: SONARR_ANIME_API_KEY
      - name: SONARR__AUTH__METHOD
        value: External

      - name: SONARR__POSTGRES__HOST
        valueFrom:
          secretKeyRef:
            name: sonarr-postgres-app
            key: host
      - name: SONARR__POSTGRES__PORT
        valueFrom:
          secretKeyRef:
            name: sonarr-postgres-app
            key: port
      - name: SONARR__POSTGRES__USER
        valueFrom:
          secretKeyRef:
            name: sonarr-postgres-app
            key: user
      - name: SONARR__POSTGRES__PASSWORD
        valueFrom:
          secretKeyRef:
            name: sonarr-postgres-app
            key: password
      - name: SONARR__POSTGRES__MAINDB
        value: sonarr_anime_main
      - name: SONARR__POSTGRES__LOGDB
        value: sonarr_anime_log

    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: media-volume
    volumeMounts:
      - name: data
        mountPath: /data
