apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
    name: sonarr
spec:
    providerConfigRef:
        name: authentik
    forProvider:
        source: Remote
        # https://github.com/typedrat/homelab/tree/12719e5d/sonarr
        module: "github.com/typedrat/homelab//sonarr?ref=12719e5d"
