apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - config.yaml
    - deployment.yaml
    - exporter-config.yaml
    - ingress-policy.yaml
    - monitoring.yaml
    - nginx-config.yaml
    - service.yaml
    - state.yaml
