apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: sftpgo-config
    namespace: media
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
