apiVersion: apps/v1
kind: Deployment
metadata:
    name: sftpgo
    namespace: media
spec:
    replicas: 1
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app: sftpgo
    template:
        metadata:
            labels:
                app: sftpgo
        spec:
            containers:
                - name: sftpgo
                  image: drakkan/sftpgo:v2.6-distroless
                  securityContext:
                      runAsUser: 911
                      runAsGroup: 911
                      fsGroup: 911
                  env: []

                  ports:
                      - containerPort: 8080
                        protocol: TCP
                        name: http
                      - containerPort: 2022
                        protocol: TCP
                        name: ssh

                  volumeMounts:
                      - name: sftpgo-config
                        mountPath: /var/lib/sftpgo
                      - name: media-shared
                        mountPath: /srv/sftpgo/data
            volumes:
                - name: sftpgo-config
                  persistentVolumeClaim:
                      claimName: sftpgo-config
                - name: media-shared
                  persistentVolumeClaim:
                      claimName: media-volume
