apiVersion: apps/v1
kind: Deployment
metadata:
    name: sftpgo
    namespace: media
spec:
    replicas: 1
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app: sftpgo
    template:
        metadata:
            labels:
                app: sftpgo
        spec:
            securityContext:
                fsGroup: 911
            containers:
                - name: sftpgo
                  image: drakkan/sftpgo:v2.6-plugins
                  securityContext:
                      runAsUser: 911
                      runAsGroup: 911
                      fsGroup: 911
                  env:
                      - name: SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN
                        value: "true"
                      - name: SFTPGO_DEFAULT_ADMIN_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: sftpgo-default-admin
                                namespace: media
                                key: username
                      - name: SFTPGO_DEFAULT_ADMIN_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: sftpgo-default-admin
                                namespace: media
                                key: password

                      - name: SFTPGO_DATA_PROVIDER__DRIVER
                        value: postgresql
                      - name: SFTPGO_DATA_PROVIDER__NAME
                        value: sftpgo
                      - name: SFTPGO_DATA_PROVIDER__HOST
                        valueFrom:
                            secretKeyRef:
                                name: sftpgo-postgres-app
                                key: host
                      - name: SFTPGO_DATA_PROVIDER__PORT
                        valueFrom:
                            secretKeyRef:
                                name: sftpgo-postgres-app
                                key: port
                      - name: SFTPGO_DATA_PROVIDER__USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: sftpgo-postgres-app
                                key: username
                      - name: SFTPGO_DATA_PROVIDER__PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: sftpgo-postgres-app
                                key: password

                      - name: SFTPGO_HTTPD__BINDINGS__0__HIDE_LOGIN_URL
                        value: "3" # don't link login URLs

                      - name: SFTPGO_HTTPD__BINDINGS__0__OIDC__CONFIG_URL
                        value: https://auth.thisratis.gay/application/o/sftpgo/
                      - name: SFTPGO_HTTPD__BINDINGS__0__OIDC__REDIRECT_BASE_URL
                        value: https://sftpgo.thisratis.gay/
                      - name: SFTPGO_HTTPD__BINDINGS__0__OIDC__USERNAME_FIELD
                        value: preferred_username
                      - name: SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_ID
                        valueFrom:
                            secretKeyRef:
                                name: sftpgo-oauth
                                namespace: media
                                key: client-id
                      - name: SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: sftpgo-oauth
                                namespace: media
                                key: client-secret

                      - name: SFTPGO_PLUGINS__0__TYPE
                        value: "auth"
                      - name: SFTPGO_PLUGINS__0__AUTH_OPTIONS__SCOPE
                        value: "1"
                      - name: SFTPGO_PLUGINS__0__CMD
                        value: "/usr/local/bin/sftpgo-plugin-auth"
                      - name: SFTPGO_PLUGINS__0__ARGS
                        value: "serve"
                      - name: SFTPGO_PLUGINS__0__AUTO_MTLS
                        value: "1"

                      - name: SFTPGO_PLUGIN_AUTH_LDAP_URL
                        value: "ldaps://ak-outpost-ldap-outpost.authentik.svc.cluster.local:636"
                      - name: SFTPGO_PLUGIN_AUTH_SKIP_TLS_VERIFY
                        value: "1"
                      - name: SFTPGO_PLUGIN_AUTH_LDAP_BASE_DN
                        value: "ou=users,ou=sftpgo,dc=ldap,dc=goauthentik,dc=io"
                      - name: SFTPGO_PLUGIN_AUTH_LDAP_BIND_DN
                        value: "cn=ldap-search,ou=users,ou=sftpgo,dc=ldap,dc=goauthentik,dc=io"
                      - name: SFTPGO_PLUGIN_AUTH_LDAP_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: sftpgo-ldap
                                namespace: media
                                key: password
                      - name: SFTPGO_PLUGIN_AUTH_LDAP_SEARCH_QUERY
                        value: "(&(memberOf=CN=Discord Users,OU=groups,OU=sftpgo,DC=ldap,DC=goauthentik,DC=io)(cn=%username%))"
                      - name: SFTPGO_PLUGIN_AUTH_PRIMARY_GROUP_PREFIX
                        value: sftpgo-
                  ports:
                      - containerPort: 8080
                        protocol: TCP
                        name: http
                      - containerPort: 2022
                        protocol: TCP
                        name: ssh

                  volumeMounts:
                      - name: sftpgo-config
                        mountPath: /var/lib/sftpgo
                      - name: media-shared
                        mountPath: /data
            volumes:
                - name: sftpgo-config
                  persistentVolumeClaim:
                      claimName: sftpgo-config
                - name: media-shared
                  persistentVolumeClaim:
                      claimName: media-volume
