apiVersion: v1
kind: Service
metadata:
    name: sftpgo
    namespace: media
spec:
    ports:
        - name: http
          port: 80
          targetPort: 8080
          protocol: TCP
        - name: ssh
          port: 22
          targetPort: 2022
          protocol: TCP
    selector:
        app: sftpgo
