apiVersion: v1
kind: Service
metadata:
    name: sftpgo
    namespace: media
spec:
    ports:
        - port: 80
          targetPort: 8080
          protocol: TCP
        - port: 22
          targetPort: 2022
          protocol: TCP
    selector:
        app: sftpgo
