apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
    name: sftpgo
spec:
    providerConfigRef:
        name: sftpgo
    forProvider:
        source: Remote
        module: "github.com/typedrat/homelab//terraform/sftpgo"
