apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: cert-manager
    namespace: kube-system
spec:
    interval: 5m
    chart:
        spec:
            chart: cert-manager
            version: ">=1.16.3 <1.17.0"
            sourceRef:
                kind: HelmRepository
                name: cert-manager
                namespace: kube-system
            interval: 1m
    values:
        crds:
            enabled: true
