apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: host-zfs-postgres
    namespace: cnpg-system
provisioner: zfs.csi.openebs.io
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
    recordsize: "8K"
    compression: "lz4"
    dedup: "off"
    fstype: "zfs"
    shared: "yes"
    poolname: "zfspv-pool"
