apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: media-flood-rtorrent
    namespace: flux-system
spec:
    interval: 10m0s
    path: ./apps/media/flood-rtorrent
    prune: true
    dependsOn:
        - name: istio-ingress
    sourceRef:
        kind: GitRepository
        name: flux-system
