apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: media-jellyfin
    namespace: flux-system
spec:
    interval: 10m0s
    path: ./apps/media/jellyfin
    prune: true
    dependsOn:
        - name: istio-ingress
        - name: authentik
    sourceRef:
        kind: GitRepository
        name: flux-system
