apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: media-prowlarr
    namespace: flux-system
spec:
    interval: 10m0s
    path: ./apps/media/prowlarr
    prune: true
    dependsOn:
        - name: istio-ingress
        - name: authentik
        - name: media-shared
    sourceRef:
        kind: GitRepository
        name: flux-system
