apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: media-shared
    namespace: flux-system
spec:
    interval: 10m0s
    path: ./apps/media/shared
    prune: true
    dependsOn:
        - name: openebs
        - name: crossplane-terraform
    sourceRef:
        kind: GitRepository
        name: flux-system
    decryption:
        provider: sops
        secretRef:
            name: sops-age
