apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: media-sonarr
    namespace: flux-system
spec:
    interval: 10m0s
    path: ./apps/media/sonarr
    prune: true
    dependsOn:
        - name: istio-ingress
        - name: authentik
        - name: media-shared
    sourceRef:
        kind: GitRepository
        name: flux-system
    decryption:
        provider: sops
        secretRef:
            name: sops-age
