apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clustersecret
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/clustersecret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
