apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/cnpg
  prune: true
  dependsOn:
    - name: openebs
  sourceRef:
    kind: GitRepository
    name: flux-system
