apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: crossplane
    namespace: flux-system
spec:
    interval: 10m0s
    path: ./infrastructure/crossplane
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: crossplane-terraform
    namespace: flux-system
spec:
    interval: 10m0s
    path: ./infrastructure/crossplane-terraform
    prune: true
    dependsOn:
        - name: crossplane
    sourceRef:
        kind: GitRepository
        name: flux-system
