apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: dragonfly-operator
    namespace: flux-system
spec:
    interval: 10m0s
    path: ./infrastructure/dragonfly-operator
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
