apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: radarr-postgres
    namespace: media
spec:
    instances: 1
    bootstrap:
        initdb:
            database: radarr_main
            owner: radarr
            dataChecksums: true
            localeCollate: "en_US"
            localeCType: "en_US"
            postInitSQL:
                - CREATE DATABASE radarr_log OWNER radarr
    storage:
        size: 1Gi
        storageClass: host-zfs-postgres
