apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: radarr-postgres
    namespace: media
spec:
    instances: 1
    bootstrap:
        initdb:
            database: radarr_main
            owner: radarr
            dataChecksums: true
            postInitSQL:
                - CREATE DATABASE radarr_log        OWNER radarr
                - CREATE DATABASE radarr_anime_main OWNER radarr
                - CREATE DATABASE radarr_anime_log  OWNER radarr
    storage:
        size: 1Gi
        storageClass: host-zfs-postgres
