apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: radarr
    namespace: media
spec:
    interval: 5m0s
    chartRef:
        kind: OCIRepository
        name: radarr
        namespace: media
    values:
        securityContext:
            runAsUser: 911
            runAsGroup: 911
        podSecurityContext:
            fsGroup: 911

        extraEnv:
            - name: RADARR__APP__INSTANCENAME
              valueFrom:
                  secretKeyRef:
                      name: radarr-secrets
                      key: instance-name

            - name: RADARR__AUTH__APIKEY
              valueFrom:
                  secretKeyRef:
                      name: radarr-secrets
                      key: api-key
            - name: RADARR__AUTH__METHOD
              value: External

            - name: RADARR__POSTGRES__HOST
              valueFrom:
                  secretKeyRef:
                      name: radarr-postgres-app
                      key: host
            - name: RADARR__POSTGRES__PORT
              valueFrom:
                  secretKeyRef:
                      name: radarr-postgres-app
                      key: port
            - name: RADARR__POSTGRES__USER
              valueFrom:
                  secretKeyRef:
                      name: radarr-postgres-app
                      key: user
            - name: RADARR__POSTGRES__PASSWORD
              valueFrom:
                  secretKeyRef:
                      name: radarr-postgres-app
                      key: password
            - name: RADARR__POSTGRES__MAINDB
              value: radarr_main
            - name: RADARR__POSTGRES__LOGDB
              value: radarr_log

        volumes:
            - name: data
              persistentVolumeClaim:
                  claimName: media-volume
        volumeMounts:
            - name: data
              mountPath: /data
