apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
    name: radarr
    namespace: media
spec:
    interval: 5m0s
    url: oci://ghcr.io/m0nsterrr/helm-charts/radarr
    ref:
        semver: ">=2.0.0 <2.1"
