apiVersion: apps/v1
kind: Deployment
metadata:
    name: prowlarr
    namespace: media
spec:
    replicas: 1
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app: prowlarr
    template:
        metadata:
            labels:
                app: prowlarr
        spec:
            initContainers:
                - name: config-setup
                  image: ghcr.io/tomwright/dasel:2-alpine
                  command: ["/bin/sh"]
                  args: ["/template/setup.sh"]
                  env:
                      - name: API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: prowlarr-api-key
                                key: api-key
                  volumeMounts:
                      - name: config
                        mountPath: /config
                      - name: template
                        mountPath: /template
            containers:
                - name: prowlarr
                  image: lscr.io/linuxserver/prowlarr:latest
                  securityContext:
                      readOnlyRootFilesystem: true
                  env:
                      - name: TZ
                        value: "America/Los_Angeles"
                  ports:
                      - containerPort: 9000
                        name: http
                  volumeMounts:
                      - name: run
                        mountPath: /run
                      - name: config
                        mountPath: /config
            securityContext:
                runAsUser: 911
                runAsGroup: 911
                fsGroup: 911
            volumes:
                - name: run
                  emptyDir:
                      medium: Memory
                - name: config
                  persistentVolumeClaim:
                      claimName: prowlarr-config
                - name: template
                  configMap:
                      name: prowlarr-config-template
