apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: prowlarr-postgres
  namespace: media
spec:
  instances: 1
  bootstrap:
    initdb:
      database: prowlarr_main
      owner: prowlarr
      dataChecksums: true
      postInitSQL:
        - CREATE DATABASE prowlarr_log OWNER prowlarr
  storage:
    size: 1Gi
    storageClass: host-zfs-postgres
