apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: prowlarr
    namespace: media
spec:
    interval: 5m0s
    chartRef:
        kind: OCIRepository
        name: prowlarr
        namespace: media
    values:
        securityContext:
            runAsUser: 911
            runAsGroup: 911
        podSecurityContext:
            fsGroup: 911

        extraEnv:
            - name: PROWLARR__APP__INSTANCENAME
              valueFrom:
                  secretKeyRef:
                      name: prowlarr-secrets
                      key: instance-name

            - name: PROWLARR__AUTH__APIKEY
              valueFrom:
                  secretKeyRef:
                      name: prowlarr-secrets
                      key: api-key
            - name: PROWLARR__AUTH__METHOD
              value: External

            - name: PROWLARR__POSTGRES__HOST
              valueFrom:
                  secretKeyRef:
                      name: prowlarr-postgres-app
                      key: host
            - name: PROWLARR__POSTGRES__PORT
              valueFrom:
                  secretKeyRef:
                      name: prowlarr-postgres-app
                      key: port
            - name: PROWLARR__POSTGRES__USER
              valueFrom:
                  secretKeyRef:
                      name: prowlarr-postgres-app
                      key: user
            - name: PROWLARR__POSTGRES__PASSWORD
              valueFrom:
                  secretKeyRef:
                      name: prowlarr-postgres-app
                      key: password
            - name: PROWLARR__POSTGRES__MAINDB
              value: prowlarr_main
            - name: PROWLARR__POSTGRES__LOGDB
              value: prowlarr_log

        config:
            persistence:
                storageClass: host-zfs-standard

        volumes:
            - name: data
              persistentVolumeClaim:
                  claimName: media-volume
        volumeMounts:
            - name: data
              mountPath: /data
