apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: community-operator
  namespace: mongodb
spec:
  interval: 1m0s
  chart:
    spec:
      chart: community-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mongodb
      version: ">=0.12.0 <0.13"
  values:
    operator:
      watchNamespace: "*"
