kind: ClusterSecret
apiVersion: clustersecret.io/v1
metadata:
    name: open-webui-clustersecret
    namespace: open-webui
matchNamespace:
    - authentik
    - open-webui
data:
    clientId: ENC[AES256_GCM,data:jtGQPzE3iPN+ON/dG4StnHxJ1qeA4PGnN2UVuHATO14su0hPjuWTu9QN10Q5yl+yDJxzlY9XMqs=,iv:uqkv/m4dx3mFOTi08aXZQxdpNgYZ1uh61kSCS7p/mVM=,tag:mFZPt559bHHoN4ot55J4Nw==,type:str]
    clientSecret: ENC[AES256_GCM,data:gH2eJk699eLaga4fLYjRZVqSSP++QXGSCY4JzXspjudZRlhqHh7Iqx39p1ht0D0MhXu/4bM/Xf7PYDAKHRh8A/B2V1yNOw/OmVjW/gDw8WMltB8d62wE/3Korj49cCUtv2KODoUXj6u0ZFqh7dcHkTlKqkTi5aAuWiIy7LO+/IHKgiYdVNr5YT6/SNtBXFQljaxjkKeO5nVEzyHRKelIy2hHEqNlVvs+z4RSNQ==,iv:85vphixtgH7lci5BOjcvmgyUhrhTw3nnWoRH3c00ymA=,tag:T+hhm7LktYm3NBsMFk1oQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pdsmvs22vq89pv0k6k9zfl3fk899cqehj2f7tx7j0tt6l66kuqssryqjlr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRG1YLyttVGNjQ0hCL0NV
            NmhqTzE3VnZVUUlZczdYdTFFdXlBSU9Ib3prCnk2TXc3YnZMZGQ1dEtzNlpXVFJk
            cEFNT1h0aWNtelNPUkZoWjJZN1FmbUkKLS0tIGE5L1pxS2V4dlZuUXZDR3VaK2xP
            Q1JGUXFhaTd4VjNsNVF5dnNvZ3UxQzQKIop8GxS47wssgCGNPTTohb/RVF2bkyxP
            gVtU2nOkAxL2eHiyYv+fuoyzgYmXSqZzXL4q2cLj2v2j5VpjHPRnFg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zjzywnjly7fm0mn22c64z5f8m45tne4ddplrrtx9q40y4kznacysvc9jxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeko1SzM4TkhQeFZpRjlF
            WHpsdUZQQzVhcGFEMmJoaWR2OHlpQXNEeDNRClV4LzB2Ujl1bUFzaXgvbFR2dzBQ
            UUF6YXdoK1R0U3hnV1dLejE5N0g3cTgKLS0tIG44MmlwdnJIb092SmZCc01EaTI1
            MmsvWnBEa292cERJR29EdjF1VFVkN0kK8DsJ9fBvh28/fWq2QWKSlQSA+b7HPCOV
            R6pl8ZjZ4NIXw7bhNvdEVOimGUg0OE2hmrDyMP+sHlX4k8USv3QH0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T16:35:13Z"
    mac: ENC[AES256_GCM,data:oSPVXxlD8/Q4v5gkrfPB3OlY4g3srw2GIhPy0aBlt87h48IwjoUsWMKA/ccHiXUHI2gY6ITYtZPrdMZ3A9pQQNiSy1UfU2mpCxbK11PBKJj4R0HCYeL6PADXeBX6ODLobj11U9reMfS/HoeQfnsJvGtGiH5v7CHx5zM2/UqpF+k=,iv:7oJc9WvNaToIafPS0wZMDALnc1qdE290Ry7nS5bhDZ8=,tag:ojQjOEz6t2xLK8zOAEQnxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
