kind: ClusterSecret
apiVersion: clustersecret.io/v1
metadata:
  name: open-webui-clustersecret
  namespace: open-webui
matchNamespace:
  - authentik
  - open-webui
stringData:
  clientId: ENC[AES256_GCM,data:D6SG8YKnAxk1PDk655kykd1wbJKdhZHmZGEnq5wPk4EhqKIJ3v4MIQ==,iv:FPe1aAHnPnm/+labk0MGuPBpXrqQ7awuXrfxwg39jAY=,tag:K9Nc6amxw3nxdtikuWNKQQ==,type:str]
  clientSecret: ENC[AES256_GCM,data:hraHggH4O8CuF0bKRT8m7oehOxQPPqksFpXta54yAwdHLbfbOZCl+ThskHdrGNc9QzfX8ok4tDkSBH3dYn8fILIMoR4jDGO2i6XrRLkiuul7+2njlz3rQo8BMFPLbndoeMldBardnMSD8k+iaVeUviFop7gYdlnKRXRPizLXRic=,iv:giKGpA29thuihB6gJvhOCBbE5l34UPnV7RdgdzjsEMY=,tag:beWC3edK2RZhQr/zCSBzEA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1pdsmvs22vq89pv0k6k9zfl3fk899cqehj2f7tx7j0tt6l66kuqssryqjlr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcUsvL1ZqdlMzOUxKZkFH
        Vk40VXFTT1pBSnNpclZ1UXREdlhlVkM2a1JnCnhHcTBnbUhHN25HOFRuZ0tOLzUv
        NGRMR2IzUSs4NVFOVXQ4RmJEMWdZbDAKLS0tIG9CRDRZMFpKRFcwZHNUZ0pya3FG
        d0p2UjQ5Y3BrUlV6Smp5OUZCbmJpVm8KZp5YthPpyUYRku+zkB//BFtH+iugx/v1
        UGq36fWfYxojsDPAI8B4tX3nr8ZSNF/Lfnz/sf3BMcilT47OFwdSbA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1zjzywnjly7fm0mn22c64z5f8m45tne4ddplrrtx9q40y4kznacysvc9jxj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUFlDM2Y1QW9BZmQ4MlNZ
        Y2dyVFZiUzNrK3VNMEtmN3Z4M3ljL1FwV1g0CnQ4eGJwdTZGbG1FYTI4Rnp4OHZ1
        TjM4REZZR3FVd1JndGVxWk4yTlhacDAKLS0tIEVxSy9uRTVJeU1RR1ZucEpubmNi
        dlJZZHVHMmZNcDNCelVTS2gwSUlKaG8KlHfpYQvEXtsYBxPLTQ5euSN6VvEHxVQQ
        gFAgvZpxsdj38ywMNG6w2xzg1guR4wNI5uNB+QV3deg29X1AtM7H8Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-16T16:25:55Z"
  mac: ENC[AES256_GCM,data:FEas7m1r331K1uZ6g9hWP5hO5DqtRBNLDFgpy0aU5EPNXyLWKfiHjeoSKdnWcOkwA8R0QFoDe6UEcXHo8Tqlc1fLVtmq9JrQyFken0ZBmPdHO8+fM1KXXFuE4ow/k/Lwa+SCMlchWqgafR7N6dLcDvwbjJgAc+cRrnm4qxMES4A=,iv:TJ6+45h0CEv/FDHgGYIaNC7OTrbk6fZGUq/JZOiyQ4o=,tag:ar+RjUEc3LEhG1yrAecxjA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
