apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: open-webui
spec:
  instances: 1
  bootstrap:
    initdb:
      database: open-webui
  storage:
    size: 2.5Gi
    storageClass: host-zfs-postgres
