apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 5m
  chart:
    spec:
      chart: open-webui
      version: ">=6.4.0 <6.5"
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: open-webui
      interval: 1m
  values:
    ollama:
      enabled: false

    tika:
      enabled: true

    websocket:
      enabled: true
      redis:
        enabled: false
      url: redis://dragonfly:6379/0

    sso:
      enable: true
      enableSignup: true
      mergeAccountsByEmail: true
      enableRoleManagement: true

      oidc:
        enabled: true
        providerName: Authentik
        providerUrl: https://auth.thisratis.gay/application/o/open-webui/.well-known/openid-configuration
        scopes: openid email profile entitlements

      roleManagement:
        rolesClaim: entitlements
        allowedRoles: user
        adminRoles: admin

    extraEnvVars:
      - name: ENABLE_PERSISTENT_CONFIG
        value: "False"
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: postgres-app
            key: uri
      - name: WEBUI_URL
        value: https://open-webui.thisratis.gay
      - name: ENABLE_SIGNUP
        value: "False"
      - name: ENABLE_LOGIN_FORM
        value: "False"
      - name: OAUTH_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: oauth
            key: clientId
      - name: OAUTH_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: oauth
            key: clientSecret
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipelines
  namespace: open-webui
spec:
  interval: 5m
  chart:
    spec:
      chart: pipelines
      version: ">=0.5.0 <0.6"
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: open-webui
      interval: 1m
  values:
    ingress: disabled
