apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-server
  namespace: minecraft
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: ">=4.24.0 <4.25"
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: minecraft
      interval: 1m
  values:
    image:
      tag: java23-graalvm

    minecraftServer:
      eula: true
      type: NEOFORGE
      version: 1.21.1
      memory: 12G
      jvmXXOpts: >
        --add-modules=jdk.incubator.vector
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=200
        -XX:+UnlockExperimentalVMOptions
        -XX:+UnlockDiagnosticVMOptions
        -XX:+DisableExplicitGC
        -XX:+AlwaysPreTouch
        -XX:G1NewSizePercent=28
        -XX:G1MaxNewSizePercent=50
        -XX:G1HeapRegionSize=16M
        -XX:G1ReservePercent=15
        -XX:G1MixedGCCountTarget=3
        -XX:InitiatingHeapOccupancyPercent=20
        -XX:G1MixedGCLiveThresholdPercent=90
        -XX:SurvivorRatio=32
        -XX:G1HeapWastePercent=5
        -XX:MaxTenuringThreshold=1
        -XX:+PerfDisableSharedMem
        -XX:G1SATBBufferEnqueueingThresholdPercent=30
        -XX:G1ConcMarkStepDurationMillis=5
        -XX:G1RSetUpdatingPauseTimePercent=0
        -XX:+UseNUMA
        -XX:-DontCompileHugeMethods
        -XX:MaxNodeLimit=240000
        -XX:NodeLimitFudgeFactor=8000
        -XX:ReservedCodeCacheSize=400M
        -XX:NonNMethodCodeHeapSize=12M
        -XX:ProfiledCodeHeapSize=194M
        -XX:NonProfiledCodeHeapSize=194M
        -XX:NmethodSweepActivity=1
        -XX:+UseFastUnorderedTimeStamps
        -XX:+UseCriticalJavaThreadPriority
        -XX:AllocatePrefetchStyle=3
        -XX:+AlwaysActAsServerClassMachine
        -XX:+UseTransparentHugePages
        -XX:LargePageSizeInBytes=2M
        -XX:+UseLargePages
        -XX:+EagerJVMCI
        -XX:+UseStringDeduplication
        -XX:+UseAES
        -XX:+UseAESIntrinsics
        -XX:+UseFMA
        -XX:+UseLoopPredicate
        -XX:+RangeCheckElimination
        -XX:+OptimizeStringConcat
        -XX:+UseCompressedOops
        -XX:+UseThreadPriorities
        -XX:+OmitStackTraceInFastThrow
        -XX:+RewriteBytecodes
        -XX:+RewriteFrequentPairs
        -XX:+UseFPUForSpilling
        -XX:+UseFastStosb
        -XX:+UseNewLongLShift
        -XX:+UseVectorCmov
        -XX:+UseXMMForArrayCopy
        -XX:+UseXmmI2D
        -XX:+UseXmmI2F
        -XX:+UseXmmLoadAndClearUpper
        -XX:+UseXmmRegToRegMoveAll
        -XX:+EliminateLocks
        -XX:+DoEscapeAnalysis
        -XX:+AlignVector
        -XX:+OptimizeFill
        -XX:+EnableVectorSupport
        -XX:+UseCharacterCompareIntrinsics
        -XX:+UseCopySignIntrinsic
        -XX:+UseVectorStubs
        -XX:UseAVX=2
        -XX:UseSSE=4
        -XX:+UseFastJNIAccessors
        -XX:+UseInlineCaches
        -XX:+SegmentedCodeCache
        -Djdk.nio.maxCachedBufferSize=262144
        -Dgraal.UsePriorityInlining=true
        -Dgraal.Vectorization=true
        -Dgraal.OptDuplication=true
        -Dgraal.DetectInvertedLoopsAsCounted=true
        -Dgraal.LoopInversion=true
        -Dgraal.VectorizeHashes=true
        -Dgraal.EnterprisePartialUnroll=true
        -Dgraal.VectorizeSIMD=true
        -Dgraal.StripMineNonCountedLoops=true
        -Dgraal.SpeculativeGuardMovement=true
        -Dgraal.TuneInlinerExploration=1
        -Dgraal.LoopRotation=true
        -Dgraal.OptWriteMotion=true
        -Dgraal.CompilerConfiguration=enterprise
      serviceType: LoadBalancer

    serviceAnnotations:
      lbipam.cilium.io/ips: 10.0.1.10

    persistence:
      dataDir:
        enabled: true
        Size: 25Gi

    rcon:
      enabled: true
      withGeneratedPassword: true
